<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\UX\Router;

use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Routing\RouteCollection;

/**
 * @author Hugo Alliaume <hugo@alliau.me>
 *
 * @final
 *
 * @internal
 */
class RoutesDumper
{
    private const JSON_FLAGS = \JSON_THROW_ON_ERROR | \JSON_UNESCAPED_SLASHES | \JSON_UNESCAPED_UNICODE;
    private const HEADER = "// This file is auto-generated by the Symfony UX Router. Do not edit it manually.\n";

    public function __construct(
        private RouteNormalizer $routeNormalizer,
        private TypeScriptRoutePrinter $typeScriptRoutePrinter,
        private Filesystem $filesystem,
    ) {
    }

    /**
     * @param list<string> $routesPatterns
     */
    public function dump(RouteCollection $routes, string $dumpDir, bool $dumpTypeScript = true, array $routesPatterns = []): void
    {
        $routeFilter = new RouteFilter($routesPatterns);
        $definitions = [];
        $declarations = [];

        foreach ($routes->all() as $name => $route) {
            if (!$routeFilter->isExposed($name, $route)) {
                continue;
            }

            $encodedName = json_encode($name, self::JSON_FLAGS);

            try {
                $definitions[] = '    '.$encodedName.': '.json_encode($this->routeNormalizer->normalize($route), self::JSON_FLAGS);
            } catch (\JsonException $e) {
                throw new \InvalidArgumentException(\sprintf('Unable to dump route "%s": "%s".', $name, $e->getMessage()), previous: $e);
            }

            if ($dumpTypeScript) {
                $declarations[] = '    '.$encodedName.': '.$this->typeScriptRoutePrinter->print($route).";\n";
            }
        }

        $this->filesystem->dumpFile(
            $dumpDir.'/index.js',
            self::HEADER."\nexport const routes = {\n".($definitions ? implode(",\n", $definitions)."\n" : '')."};\n",
        );

        if ($dumpTypeScript) {
            $this->filesystem->dumpFile(
                $dumpDir.'/index.d.ts',
                self::HEADER."import type { Route } from '@symfony/ux-router';\n\nexport declare const routes: {\n".implode('', $declarations)."};\n",
            );
        } else {
            $this->filesystem->remove($dumpDir.'/index.d.ts');
        }
    }
}
