packages:
  - src/*/assets
  - src/*/src/Bridge/*/assets

linkWorkspacePackages: true

packageExtensions:
    '@symfony/ux-google-map':
      dependencies:
        '@symfony/ux-map': 'workspace:*'

    '@symfony/ux-leaflet-map':
      dependencies:
        '@symfony/ux-map': 'workspace:*'
