packages:
  - src/*/assets
  - src/*/src/Bridge/*/assets

linkWorkspacePackages: true

overrides:
  '@swup/plugin>@swup/browserslist-config': link:node_modules/.ignored
  '@swup/plugin>@swup/prettier-config': link:node_modules/.ignored
  '@swup/plugin>microbundle': link:node_modules/.ignored
  '@swup/plugin>prettier': link:node_modules/.ignored
  '@swup/plugin>shelljs': link:node_modules/.ignored
  '@swup/plugin>shelljs-live': link:node_modules/.ignored

packageExtensions:
    '@symfony/ux-google-map':
      dependencies:
        '@symfony/ux-map': 'workspace:*'

    '@symfony/ux-leaflet-map':
      dependencies:
        '@symfony/ux-map': 'workspace:*'
