framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        excluded_patterns:
            - '*/assets/react/src/**'
            - '*/assets/react/node_modules/**'
            - '*/assets/svelte/src/**'
            - '*/assets/svelte/node_modules/**'
        missing_import_mode: strict
        importmap_polyfill: false

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
