ux_translator:
    # The directory where the JavaScript translations are dumped
    dump_directory: '%kernel.project_dir%/var/translations'

    # The translation domains to include in the dump
    domains:
        - messages
