// This file is auto-generated by the Symfony UX Router. Do not edit it manually.
import type { Route } from '@symfony/ux-router';

export declare const routes: {
    "app_home": Route;
    "app_blog_list": Route<{ "page"?: string | number }>;
    "app_blog_show": Route<{ "slug": string | number }>;
    "app_about.en": Route<{ "_locale"?: "en" }, "app_about">;
    "app_about.fr": Route<{ "_locale"?: "fr" }, "app_about">;
    "app_lang": Route<{ "_locale"?: "en" | "fr" }>;
    "app_host": Route<{ "subdomain"?: "www" | "m" }>;
    "app_secure": Route;
    "app_controller": Route;
    "legacy_search": Route;
};
