<?php

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    'app-react' => [
        'path' => './assets/app-react.js',
        'entrypoint' => true,
    ],
    'app-svelte' => [
        'path' => './assets/app-svelte.js',
        'entrypoint' => true,
    ],
    'app-vue' => [
        'path' => './assets/app-vue.js',
        'entrypoint' => true,
    ],
    '@symfony/stimulus-bundle' => [
        'path' => '@symfony/stimulus-bundle/loader.js',
    ],
    '@symfony/ux-react' => [
        'path' => '@symfony/ux-react/loader.js',
    ],
    '@symfony/ux-vue' => [
        'path' => '@symfony/ux-vue/loader.js',
    ],
    '@symfony/ux-svelte' => [
        'path' => '@symfony/ux-svelte/loader.js',
    ],
    '@symfony/ux-translator' => [
        'path' => '@symfony/ux-translator/translator_controller.js',
    ],
    '@app/translations' => [
        'path' => 'var/translations/index.js',
    ],
    '@app/translations/configuration' => [
        'path' => 'var/translations/configuration.js',
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'stimulus-clipboard' => [
        'version' => '3.3.0',
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.1',
    ],
    'tom-select' => [
        'version' => '2.2.2',
    ],
    'react' => [
        'version' => '18.2.0',
    ],
    'react-dom' => [
        'version' => '18.2.0',
    ],
    'vue' => [
        'version' => '3.3.0',
        'package_specifier' => 'vue/dist/vue.esm-bundler.js',
    ],
    'swup' => [
        'version' => '3.0.6',
    ],
    'delegate-it' => [
        'version' => '3.0.1',
    ],
    '@swup/debug-plugin' => [
        'version' => '3.0.0',
    ],
    '@swup/fade-theme' => [
        'version' => '1.0.5',
    ],
    '@swup/forms-plugin' => [
        'version' => '2.0.1',
    ],
    '@swup/slide-theme' => [
        'version' => '1.0.5',
    ],
    '@swup/plugin' => [
        'version' => '2.0.2',
    ],
    '@hotwired/turbo' => [
        'version' => '7.3.0',
    ],
    'typed.js' => [
        'version' => '2.0.16',
    ],
    'snarkdown' => [
        'version' => '2.0.0',
    ],
    'chart.js/auto' => [
        'version' => '3.9.1',
    ],
    'cropperjs' => [
        'version' => '1.5.13',
    ],
    'svelte/transition' => [
        'version' => '3.59.1',
    ],
    'svelte/animate' => [
        'version' => '3.59.1',
    ],
    'svelte/internal' => [
        'version' => '3.59.1',
    ],
    'highlight.js/lib/core' => [
        'version' => '11.7.0',
    ],
    'highlight.js/lib/languages/javascript' => [
        'version' => '11.7.0',
    ],
    'highlight.js/lib/languages/php' => [
        'version' => '11.7.0',
    ],
    'highlight.js/lib/languages/twig' => [
        'version' => '11.7.0',
    ],
    'highlight.js/lib/languages/xml' => [
        'version' => '11.7.0',
    ],
    'intl-messageformat' => [
        'version' => '10.3.5',
    ],
    '@vue/runtime-dom' => [
        'version' => '3.3.4',
    ],
    '@vue/runtime-core' => [
        'version' => '3.3.4',
    ],
    '@vue/shared' => [
        'version' => '3.3.4',
    ],
    '@vue/reactivity' => [
        'version' => '3.3.4',
    ],
    '@vue/compiler-dom' => [
        'version' => '3.3.4',
    ],
    '@vue/compiler-core' => [
        'version' => '3.3.4',
    ],
    'tslib' => [
        'version' => '2.6.2',
    ],
    '@formatjs/icu-messageformat-parser' => [
        'version' => '2.6.2',
    ],
    '@formatjs/icu-skeleton-parser' => [
        'version' => '1.6.2',
    ],
    '@formatjs/fast-memoize' => [
        'version' => '2.2.0',
    ],
    'tom-select/dist/css/tom-select.bootstrap5.css' => [
        'version' => '2.3.1',
        'type' => 'css',
    ],
    'cropperjs/dist/cropper.min.css' => [
        'version' => '1.6.1',
        'type' => 'css',
    ],
    'scheduler' => [
        'version' => '0.23.0',
    ],
];
