<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\UX\LiveComponent;

/**
 * Returned from a LiveAction to ask the browser for something the render alone cannot express.
 *
 * This is not an HTTP response: LiveComponentSubscriber turns it into one, alongside the
 * re-rendered component. That is the whole point: the component still renders, so whatever
 * the action changed is applied on the page even though a file was downloaded.
 *
 *     #[LiveAction]
 *     public function export(): LiveResponse
 *     {
 *         ++$this->exportCount; // still shown after the download
 *
 *         return LiveResponse::downloadUrl($this->generateUrl('app_export_download'));
 *     }
 *
 * Can only be returned from a LiveAction or a LiveListener, over POST. Returning one from the
 * default action throws, as that action runs on every re-render: a polling component would
 * otherwise download a file on every tick.
 *
 * @author Simon André <smn.andre@gmail.com>
 * @author Kevin Bond <kevinbond@gmail.com>
 *
 * @see https://symfony.com/bundles/ux-live-component/current/index.html#downloading-files
 */
final class LiveResponse
{
    private const DEFAULT_CONTENT_TYPE = 'application/octet-stream';

    /**
     * @param string|\SplFileInfo|resource|\Closure|null $content
     */
    private function __construct(
        public readonly mixed $content = null,
        public readonly ?string $filename = null,
        public readonly ?string $contentType = null,
        public readonly ?int $size = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * Points the browser at a URL it downloads itself.
     *
     * Prefer this whenever the content can be served by its own route: the download is native,
     * so it costs no memory on either side, reports progress, supports range requests and
     * resuming, and can be access-controlled and logged on its own.
     *
     * The component re-renders as usual; only the download happens outside of the response.
     *
     * @param string $url Any URL the browser can fetch, typically a route generated by the app
     *
     * @throws \InvalidArgumentException if $url is empty
     */
    public static function downloadUrl(string $url): self
    {
        if ('' === trim($url)) {
            throw new \InvalidArgumentException('The download URL cannot be empty.');
        }

        return new self(url: $url);
    }

    /**
     * Sends a file along with the re-rendered component, in a single response.
     *
     * Use it when no URL can serve the content, typically because the action builds it and it
     * would have to be stored first. The browser buffers the whole thing before saving it,
     * whatever the server does, which suits reports and exports rather than huge files.
     *
     * Everything but a string is streamed, so the file is never held in memory server-side.
     *
     * @param string|\SplFileInfo|resource|\Closure $content     The contents as a string (never a
     *                                                           path), a file, a stream, or a
     *                                                           closure that echoes them or
     *                                                           returns an iterable
     * @param string|null                           $filename    Required, except for an
     *                                                           \SplFileInfo, whose basename is
     *                                                           used
     * @param string|null                           $contentType Defaults to
     *                                                           "application/octet-stream"; it is
     *                                                           never guessed from the content
     * @param int|null                              $size        Size in bytes, only for a stream
     *                                                           or a closure: it is deduced for a
     *                                                           string and an \SplFileInfo. Pass
     *                                                           it whenever known, as it is what
     *                                                           gives the response a
     *                                                           Content-Length, and the browser a
     *                                                           progress bar
     *
     * @throws \InvalidArgumentException if $content is of an unsupported type, if $filename is
     *                                   missing or blank, if $size contradicts the actual size,
     *                                   or if $contentType contains a line break
     */
    public static function downloadFile(mixed $content, ?string $filename = null, ?string $contentType = null, ?int $size = null): self
    {
        $deducedSize = null;

        if (\is_string($content)) {
            $deducedSize = \strlen($content);
        } elseif ($content instanceof \SplFileInfo) {
            // SplFileObject::__toString() returns the current line, so the basename must come
            // from the path, and getSize() throws on a stream-backed object
            $filename ??= $content->getBasename();
            $deducedSize = $content->isFile() ? $content->getSize() : null;
        } elseif (!\is_resource($content) && !$content instanceof \Closure) {
            throw new \InvalidArgumentException(\sprintf('The content must be a string, an \SplFileInfo, a resource or a closure, "%s" given.', get_debug_type($content)));
        }

        if (null === $filename || '' === trim($filename)) {
            throw new \InvalidArgumentException('A filename is required, and can only be omitted when the content is an \SplFileInfo.');
        }

        if (null !== $deducedSize && null !== $size && $size !== $deducedSize) {
            // an inexact Content-Length truncates the response or leaves the client waiting
            throw new \InvalidArgumentException(\sprintf('The given size (%d) does not match the actual content size (%d).', $size, $deducedSize));
        }

        $contentType ??= self::DEFAULT_CONTENT_TYPE;

        if (preg_match('/[\r\n]/', $contentType)) {
            throw new \InvalidArgumentException('The content type cannot contain a line break.');
        }

        return new self($content, $filename, $contentType, $size ?? $deducedSize);
    }

    /**
     * Whether the browser fetches the file itself, rather than receiving it with the render.
     *
     * @internal
     */
    public function isDownloadUrl(): bool
    {
        return null !== $this->url;
    }
}
