<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\UX\Css\Reference;

use Symfony\UX\Css\Validation\StyleValidator;

/**
 * Writes the PHPDoc types of the hash css() takes, from the tokens, conditions and keywords of the project.
 *
 * The hash under a condition or a breakpoint is left untyped: PHPStan refuses a type alias that refers to itself,
 * and each nested level written out makes its analysis much slower.
 *
 * @author Hugo Alliaume <hugo@alliau.me>
 *
 * @internal
 */
final class ReferenceDumper
{
    private const TEMPLATE = <<<'PHP'
        <?php

        // This file is auto-generated by symfony/ux-css. Do not edit.

        namespace Symfony\UX\Css;

        /**
        {TYPES}
         */
        final class CssReference
        {
        }

        PHP;

    public function __construct(
        private readonly StyleValidator $validator,
    ) {
    }

    public function dump(): string
    {
        $aliases = [];
        $aliasOfType = [];
        $properties = [];
        foreach ($this->validator->propertyNames() as $key) {
            $type = $this->valueType($key, $aliases, $aliasOfType);
            $properties[$key] = $type.'|array<'.$type.'|array<array-key, mixed>>';
        }
        ksort($aliases, \SORT_STRING);

        $lines = [];
        foreach ($aliases as $name => $type) {
            $lines[] = \sprintf(' * @psalm-type %s = %s', $name, $type);
        }
        array_push($lines, ...$this->hashType($properties));

        return strtr(self::TEMPLATE, ['{TYPES}' => implode("\n", $lines)]);
    }

    /**
     * @param array<string, string> $aliases     the value types written as aliases, by name
     * @param array<string, string> $aliasOfType the name of each alias, by type
     */
    private function valueType(string $key, array &$aliases, array &$aliasOfType): string
    {
        $values = $this->validator->valuesOf($key);

        $members = [];
        foreach ($values['literals'] as $literal) {
            if (!str_contains($literal, "'") && !str_contains($literal, '\\')) {
                $members[] = "'".$literal."'";
            }
        }
        if ($values['number']) {
            array_push($members, 'int', 'float');
        }
        if ($values['boolean']) {
            $members[] = 'bool';
        }
        $members[] = 'string';
        $type = implode('|', $members);

        if (!str_contains($type, "'")) {
            return $type;
        }
        if (isset($aliasOfType[$type])) {
            return $aliasOfType[$type];
        }

        $name = self::aliasName($values['property'], $values['category'], $aliases);
        $aliases[$name] = $type;
        $aliasOfType[$type] = $name;

        return $name;
    }

    /**
     * @param array<string, string> $aliases
     */
    private static function aliasName(string $property, ?string $category, array $aliases): string
    {
        $base = null !== $category ? ucfirst($category).'Token' : ucfirst($property).'Value';
        $name = $base;
        for ($suffix = 2; isset($aliases[$name]); ++$suffix) {
            $name = $base.$suffix;
        }

        return $name;
    }

    /**
     * @param array<string, string> $properties the value type of each property
     *
     * @return list<string>
     */
    private function hashType(array $properties): array
    {
        $lines = [' * @psalm-type CssStyles = array{'];
        foreach ($properties as $key => $type) {
            $lines[] = \sprintf(' *     %s?: %s,', self::key($key), $type);
        }
        foreach ($this->validator->conditionKeys() as $key) {
            if (!str_contains($key, "'") && !str_contains($key, '\\')) {
                $lines[] = \sprintf(' *     %s?: %s,', self::key($key), 'array<string, mixed>');
            }
        }
        $lines[] = ' * }';

        return $lines;
    }

    private static function key(string $key): string
    {
        return preg_match('/^[a-zA-Z_][a-zA-Z0-9_]*$/', $key) ? $key : "'".$key."'";
    }
}
