<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\UX\Router\Tests;

use PHPUnit\Framework\TestCase;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Routing\Loader\PhpFileLoader;
use Symfony\Component\Routing\Route;
use Symfony\Component\Routing\RouteCollection;
use Symfony\UX\Router\RouteNormalizer;
use Symfony\UX\Router\RoutesDumper;
use Symfony\UX\Router\TypeScriptRoutePrinter;

final class RoutesDumperTest extends TestCase
{
    use ParsesDumpedRoutesTrait;

    private const FIXTURES_DIR = __DIR__.'/../assets/test/fixtures/routes';
    private const HEADER = "// This file is auto-generated by the Symfony UX Router. Do not edit it manually.\n";

    private string $dumpDir;

    protected function setUp(): void
    {
        $this->dumpDir = sys_get_temp_dir().'/ux_router_dumper_'.bin2hex(random_bytes(4));
    }

    protected function tearDown(): void
    {
        new Filesystem()->remove($this->dumpDir);
    }

    public function testDumpMatchesCommittedFixtures(): void
    {
        $this->createDumper()->dump(self::loadFixtureRoutes(), $this->dumpDir, true, ['app_*', '!app_admin_*']);

        foreach (['index.js', 'index.d.ts'] as $file) {
            if (getenv('UPDATE_FIXTURES')) {
                new Filesystem()->copy($this->dumpDir.'/'.$file, self::FIXTURES_DIR.'/'.$file, true);
            }

            self::assertFileEquals(self::FIXTURES_DIR.'/'.$file, $this->dumpDir.'/'.$file, 'Run "UPDATE_FIXTURES=1 vendor/bin/phpunit" to update the fixtures.');
        }
    }

    public function testDumpsOnlyExposedRoutes(): void
    {
        $this->createDumper()->dump(self::loadFixtureRoutes(), $this->dumpDir, true, ['app_*', '!app_admin_*']);

        self::assertSame(
            ['app_home', 'app_blog_list', 'app_blog_show', 'app_about.en', 'app_about.fr', 'app_lang', 'app_host', 'app_secure', 'app_controller', 'legacy_search'],
            array_keys(self::parseDumpedRoutes($this->dumpDir.'/index.js')),
        );
    }

    public function testDoesNotLeakControllers(): void
    {
        $this->createDumper()->dump(self::loadFixtureRoutes(), $this->dumpDir, true, ['app_*']);

        self::assertStringNotContainsString('SecretController', file_get_contents($this->dumpDir.'/index.js'));
        self::assertStringNotContainsString('"_controller"', file_get_contents($this->dumpDir.'/index.js'));
    }

    public function testDumpWithoutTypeScriptRemovesStaleDeclarations(): void
    {
        $dumper = $this->createDumper();
        $dumper->dump(self::loadFixtureRoutes(), $this->dumpDir, true, ['app_*']);
        self::assertFileExists($this->dumpDir.'/index.d.ts');

        $dumper->dump(self::loadFixtureRoutes(), $this->dumpDir, false, ['app_*']);
        self::assertFileExists($this->dumpDir.'/index.js');
        self::assertFileDoesNotExist($this->dumpDir.'/index.d.ts');
    }

    public function testDumpWithoutExposedRoutes(): void
    {
        $routes = new RouteCollection();
        $routes->add('app_home', new Route('/'));

        $this->createDumper()->dump($routes, $this->dumpDir);

        self::assertStringEqualsFile($this->dumpDir.'/index.js', self::HEADER."\nexport const routes = {\n};\n");
        self::assertStringEqualsFile($this->dumpDir.'/index.d.ts', self::HEADER."import type { Route } from '@symfony/ux-router';\n\nexport declare const routes: {\n};\n");
    }

    public function testEscapesRouteNames(): void
    {
        $routes = new RouteCollection();
        $routes->add('app_"quoted"\\name', new Route('/a'));
        $routes->add('app_café', new Route('/b'));

        $this->createDumper()->dump($routes, $this->dumpDir, true, ['app_*']);

        self::assertSame(['app_"quoted"\\name', 'app_café'], array_keys(self::parseDumpedRoutes($this->dumpDir.'/index.js')));
        self::assertStringContainsString('"app_\"quoted\"\\\\name": Route;', file_get_contents($this->dumpDir.'/index.d.ts'));
    }

    public function testDumpFailsOnADefaultJsonCannotEncode(): void
    {
        $routes = new RouteCollection();
        $routes->add('app_nan', new Route('/{value}', ['value' => \NAN]));

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Unable to dump route "app_nan": "Inf and NaN cannot be JSON encoded".');

        $this->createDumper()->dump($routes, $this->dumpDir, true, ['app_*']);
    }

    private function createDumper(): RoutesDumper
    {
        return new RoutesDumper(new RouteNormalizer(), new TypeScriptRoutePrinter(), new Filesystem());
    }

    private static function loadFixtureRoutes(): RouteCollection
    {
        return new PhpFileLoader(new FileLocator(__DIR__.'/Fixtures'))->load('routes.php');
    }
}
