<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Symfony\UX\Translator;

use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Translation\MessageCatalogueInterface;
use Symfony\UX\Translator\MessageParameters\Extractor\IntlMessageParametersExtractor;
use Symfony\UX\Translator\MessageParameters\Extractor\MessageParametersExtractor;
use Symfony\UX\Translator\MessageParameters\Printer\TypeScriptMessageParametersPrinter;

/**
 * @author Hugo Alliaume <hugo@alliau.me>
 *
 * @final
 *
 * @experimental
 *
 * @phpstan-type Domain string
 * @phpstan-type Locale string
 * @phpstan-type MessageId string
 */
class TranslationsDumper
{
    public function __construct(
        private MessageParametersExtractor $messageParametersExtractor,
        private IntlMessageParametersExtractor $intlMessageParametersExtractor,
        private TypeScriptMessageParametersPrinter $typeScriptMessageParametersPrinter,
        private Filesystem $filesystem,
    ) {
    }

    /**
     * @param list<MessageCatalogueInterface> $catalogues
     * @param list<Domain>                    $includedDomains
     * @param list<Domain>                    $excludedDomains
     * @param list<string>                    $keysPatterns
     */
    public function dump(
        array $catalogues,
        string $dumpDir,
        bool $dumpTypeScript = true,
        array $includedDomains = [],
        array $excludedDomains = [],
        array $keysPatterns = [],
    ): void {
        if ($includedDomains && $excludedDomains) {
            throw new \LogicException('You cannot set both "excluded_domains" and "included_domains" at the same time.');
        }

        $includedKeysPatterns = [];
        $excludedKeysPatterns = [];
        foreach ($keysPatterns as $pattern) {
            if (str_starts_with($pattern, '!')) {
                $excludedKeysPatterns[] = substr($pattern, 1);
            } else {
                $includedKeysPatterns[] = $pattern;
            }
        }

        $includeKeysRegex = $this->buildPatternRegex($includedKeysPatterns);
        $excludeKeysRegex = $this->buildPatternRegex($excludedKeysPatterns);

        $this->filesystem->mkdir($dumpDir);
        $this->filesystem->remove($fileIndexJs = $dumpDir.'/index.js');
        $this->filesystem->remove($fileIndexDts = $dumpDir.'/index.d.ts');

        $this->filesystem->appendToFile(
            $fileIndexJs,
            \sprintf(<<<'JS'
                // This file is auto-generated by the Symfony UX Translator. Do not edit it manually.

                export const localeFallbacks = %s;
                export const messages = {

                JS,
                json_encode($this->getLocaleFallbacks($catalogues), \JSON_THROW_ON_ERROR)
            ));

        if ($dumpTypeScript) {
            $this->filesystem->appendToFile(
                $fileIndexDts,
                <<<'TS'
                    // This file is auto-generated by the Symfony UX Translator. Do not edit it manually.
                    import { Message, NoParametersType, LocaleType } from '@symfony/ux-translator';

                    export declare const localeFallbacks: Record<LocaleType, LocaleType>;
                    export declare const messages: {

                    TS
            );
        }

        foreach ($this->getTranslations($catalogues, $excludedDomains, $includedDomains, $includeKeysRegex, $excludeKeysRegex) as $translationId => $translationsByDomainAndLocale) {
            $translationId = str_replace('"', '\\"', $translationId);
            $this->filesystem->appendToFile($fileIndexJs, \sprintf(
                '    "%s": %s,%s',
                $translationId,
                json_encode(['translations' => $translationsByDomainAndLocale], \JSON_THROW_ON_ERROR),
                "\n"
            ));

            if ($dumpTypeScript) {
                $this->filesystem->appendToFile($fileIndexDts, \sprintf(
                    '    "%s": %s;%s',
                    $translationId,
                    $this->getTranslationsTypeScriptTypeDefinition($translationsByDomainAndLocale),
                    "\n"
                ));
            }
        }

        $this->filesystem->appendToFile($fileIndexJs, '};'."\n");

        if ($dumpTypeScript) {
            $this->filesystem->appendToFile($fileIndexDts, '};'."\n");
        }
    }

    /**
     * @param list<MessageCatalogueInterface> $catalogues
     * @param list<Domain>                    $excludedDomains
     * @param list<Domain>                    $includedDomains
     *
     * @return array<MessageId, array<Domain, array<Locale, string>>>
     */
    private function getTranslations(array $catalogues, array $excludedDomains, array $includedDomains, ?string $includeKeysRegex, ?string $excludeKeysRegex): array
    {
        $translations = [];

        foreach ($catalogues as $catalogue) {
            $locale = $catalogue->getLocale();
            foreach ($catalogue->getDomains() as $domain) {
                if (\in_array($domain, $excludedDomains, true)) {
                    continue;
                }
                if ($includedDomains && !\in_array($domain, $includedDomains, true)) {
                    continue;
                }
                foreach ($catalogue->all($domain) as $id => $message) {
                    // Filter by keys patterns
                    if ($excludeKeysRegex && preg_match($excludeKeysRegex, $id)) {
                        continue;
                    }
                    if ($includeKeysRegex && !preg_match($includeKeysRegex, $id)) {
                        continue;
                    }

                    $realDomain = $catalogue->has($id, $domain.MessageCatalogueInterface::INTL_DOMAIN_SUFFIX)
                        ? $domain.MessageCatalogueInterface::INTL_DOMAIN_SUFFIX
                        : $domain;

                    $translations[$id] ??= [];
                    $translations[$id][$realDomain] ??= [];
                    $translations[$id][$realDomain][$locale] = $message;
                }
            }
        }

        return $translations;
    }

    /**
     * @param array<Domain, array<Locale, string>> $translationsByDomainAndLocale
     *
     * @throws \Exception
     */
    private function getTranslationsTypeScriptTypeDefinition(array $translationsByDomainAndLocale): string
    {
        $parametersTypes = [];
        $locales = [];

        foreach ($translationsByDomainAndLocale as $domain => $translationsByLocale) {
            foreach ($translationsByLocale as $locale => $translation) {
                try {
                    $parameters = str_ends_with($domain, MessageCatalogueInterface::INTL_DOMAIN_SUFFIX)
                        ? $this->intlMessageParametersExtractor->extract($translation)
                        : $this->messageParametersExtractor->extract($translation);
                } catch (\Throwable $e) {
                    throw new \Exception(\sprintf('Error while extracting parameters from message "%s" in domain "%s" and locale "%s".', $translation, $domain, $locale), previous: $e);
                }

                $parametersTypes[$domain] = $this->typeScriptMessageParametersPrinter->print($parameters);
                $locales[] = $locale;
            }
        }

        $typeScriptParametersType = [];
        foreach ($parametersTypes as $domain => $parametersType) {
            $typeScriptParametersType[] = \sprintf("'%s': { parameters: %s }", $domain, $parametersType);
        }

        return \sprintf(
            'Message<{ %s }, %s>',
            implode(', ', $typeScriptParametersType),
            implode('|', array_map(static fn (string $locale) => "'$locale'", array_unique($locales))),
        );
    }

    /**
     * @param list<MessageCatalogueInterface> $catalogues
     */
    private function getLocaleFallbacks(array $catalogues): array
    {
        $localesFallbacks = [];

        foreach ($catalogues as $catalogue) {
            $localesFallbacks[$catalogue->getLocale()] = $catalogue->getFallbackCatalogue()?->getLocale();
        }

        return $localesFallbacks;
    }

    /**
     * @param list<string> $patterns
     */
    private function buildPatternRegex(array $patterns): ?string
    {
        if ([] === $patterns) {
            return null;
        }

        // Filter empty patterns and deduplicate
        $patterns = array_reduce($patterns, static function (array $carry, string $pattern) {
            $trimmed = trim($pattern);
            if ('' !== $trimmed && !\in_array($trimmed, $carry, true)) {
                $carry[] = $trimmed;
            }

            return $carry;
        }, []);

        if ([] === $patterns) {
            return null;
        }

        // If a pattern is just '*', match everything
        if (\in_array('*', $patterns, true)) {
            return '/^.*$/';
        }

        $regexPatterns = [];
        foreach ($patterns as $pattern) {
            $regexPatterns[] = str_replace('\\*', '.*', preg_quote($pattern, '/'));
        }

        $compiledRegex = '/^(?:'.implode('|', $regexPatterns).')$/';

        if (false === preg_match($compiledRegex, '')) {
            throw new \InvalidArgumentException(\sprintf('The patterns "%s" resulted in an invalid regex. Error "%s".', implode('", "', $patterns), preg_last_error_msg()));
        }

        return $compiledRegex;
    }
}
