controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_blog_show:
    path: /blog/{slug}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: base.html.twig
