name: App Code Quality

on:
    push:
        paths:
            - 'apps/**'
            - '.github/workflows/app-code-quality.yaml'
    pull_request:
        paths:
            - 'apps/**'
            - '.github/workflows/app-code-quality.yaml'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
  code-formatting:
    name: "Code Formatting (${{ matrix.app }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ['e2e']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install root dependencies
        uses: ramsey/composer-install@v3
        with:
            working-directory: ${{ github.workspace }}

      - name: Build root packages
        run: php .github/build-packages.php

      - name: Install composer packages
        uses: ramsey/composer-install@v3
        with:
          working-directory: apps/${{ matrix.app }}

      - name: Ensure PHP code style
        run: php vendor/bin/php-cs-fixer fix --diff --dry-run
        working-directory: apps/${{ matrix.app }}

      - name: Ensure Twig files are nicely formatted
        run: php vendor/bin/twig-cs-fixer lint
        working-directory: apps/${{ matrix.app }}
