name: Dist Files Size Diff (Comment)

on:
    workflow_run:
        workflows: ['Dist Files Size Diff']
        types:
            - completed

permissions:
    contents: read # Required to checkout the repository (default)
    actions: read # Required to download artifacts from the triggering workflow run
    pull-requests: write # Required to post the size diff comment on the pull request

jobs:
    dist-files-size-diff:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@484a0b528fb4d7bd804637ccb632e47a0e638317
              with:
                  name: dist-size-diff
                  run-id: ${{ github.event.workflow_run.id }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Read pr-number artifact to env var
              id: read-pr-number
              run: |
                  PR_NUMBER=$(cat ./pr-number)
                  if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
                      echo "Invalid PR number: $PR_NUMBER"
                      exit 1
                  fi
                  echo "pr-number=$PR_NUMBER" >> $GITHUB_OUTPUT

            - name: Comment on the pull request (if success)
              uses: marocchino/sticky-pull-request-comment@0ea0beb66eb9baf113663a64ec522f60e49231c0
              with:
                  number: ${{ steps.read-pr-number.outputs.pr-number }}
                  path: ./diff.md
