name: Dist Files Unbuilt

on:
    push:
        branches-ignore:
            - 'dependabot/**'
        paths-ignore:
            - 'apps/**'
            - 'src/*/doc/**'
            - 'src/**/*.md'
    pull_request:
        paths-ignore:
            - 'apps/**'
            - 'src/*/doc/**'
            - 'src/**/*.md'

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions: {}

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
              with:
                  cache: true

            - name: Build
              run: pnpm run build

            - name: Check if JS dist files are current
              run: |
                  if ! git diff --quiet; then
                    echo "The Git workspace is unclean! Changes detected:"
                    git status --porcelain
                    git diff
                    exit 1
                  else
                    echo "The Git workspace is clean. No changes detected."
                  fi
