name: RST Linter

on:
    push:
        branches-ignore:
            - 'dependabot/**'
        paths:
            - '**.rst'
            - 'src/*/doc/**'
    pull_request:
        paths:
            - '**.rst'
            - 'src/*/doc/**'

permissions: {}

jobs:
    doctor-rst:
        name: DOCtor-RST
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
              with:
                  persist-credentials: false

            - name: Create cache dir
              run: mkdir .cache

            - name: Extract base branch name
              run: echo "branch=$(echo ${GITHUB_BASE_REF:=${GITHUB_REF##*/}})" >> $GITHUB_OUTPUT
              id: extract_base_branch

            - name: Cache DOCtor-RST
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
              with:
                  path: .cache
                  key: doctor-rst-${{ steps.extract_base_branch.outputs.branch }}

            - name: DOCtor-RST
              uses: docker://oskarstark/doctor-rst
              with:
                  args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache
