name: RST Linter

on:
    push:
        branches-ignore:
            - 'dependabot/**'
        paths:
            - '**.rst'
            - 'src/*/doc/**'
    pull_request:
        paths:
            - '**.rst'
            - 'src/*/doc/**'

permissions: {}

jobs:
    doctor-rst:
        name: DOCtor-RST
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Create cache dir
              run: mkdir .cache

            - name: Extract base branch name
              run: echo "branch=$(echo ${GITHUB_BASE_REF:=${GITHUB_REF##*/}})" >> $GITHUB_OUTPUT
              id: extract_base_branch

            - name: Cache DOCtor-RST
              uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
              with:
                  path: .cache
                  key: doctor-rst-${{ steps.extract_base_branch.outputs.branch }}

            - name: DOCtor-RST
              uses: docker://oskarstark/doctor-rst@sha256:bf0e72e974ee41e9a3c4aeee65a73fc0554a1d08860cf7cba80096d5ad8e8108 # 1.84.0
              with:
                  args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache
