name: RST Linter

on:
    push:
        paths:
            - '**.rst'
            - 'src/*/doc/**'
    pull_request:
        paths:
            - '**.rst'
            - 'src/*/doc/**'

jobs:
    doctor-rst:
        name: DOCtor-RST
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create cache dir
              run: mkdir .cache

            - name: Extract base branch name
              run: echo "branch=$(echo ${GITHUB_BASE_REF:=${GITHUB_REF##*/}})" >> $GITHUB_OUTPUT
              id: extract_base_branch

            - name: Cache DOCtor-RST
              uses: actions/cache@v4
              with:
                  path: .cache
                  key: doctor-rst-${{ steps.extract_base_branch.outputs.branch }}

            - name: DOCtor-RST
              uses: docker://oskarstark/doctor-rst
              with:
                  args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache
