name: Toolkit Kits Code Quality

on:
    push:
        paths:
            - 'src/Toolkit/kits/**'
    pull_request:
        paths:
            - 'src/Toolkit/kits/**'

jobs:
    kits-cs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2

            - name: Get Composer Cache Directory
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-kits-${{ hashFiles('composer.json') }}
                restore-keys: |
                  ${{ runner.os }}-composer-kits-

            - name: Install composer packages
              run: composer install
              working-directory: src/Toolkit

            - name: Check kits code style
              run: php vendor/bin/twig-cs-fixer check kits
              working-directory: src/Toolkit
