name: ux.symfony.com

on:
    push:
        paths:
            - 'ux.symfony.com/**'
            - 'src/*/**'
            - '!src/*/doc/**'
            - '!src/**/*.md'
            - '.github/**'
    pull_request:
        paths:
            - 'ux.symfony.com/**'
            - 'src/*/**'
            - '!src/*/doc/**'
            - '!src/**/*.md'
            - '.github/**'

jobs:

    cs-php:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ux.symfony.com
        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'
                    tools: php-cs-fixer

            -   uses: ./.github/actions/install-website-dependencies

            -   name: php-cs-fixer
                run: php-cs-fixer check --diff

    cs-twig:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ux.symfony.com
        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'

            -   uses: ./.github/actions/install-website-dependencies

            -   name: twig-cs-fixer
                run: vendor/bin/twig-cs-fixer lint templates --report=github

    tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ux.symfony.com
        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.3'

            -   uses: ./.github/actions/install-root-dependencies

            -   name: Build root packages
                run: php .github/build-packages.php
                working-directory: ${{ github.workspace }}

            -   uses: ./.github/actions/install-website-dependencies
                with:
                    dependency-versions: 'highest'

            -   name: Importmap dependencies
                run: php bin/console importmap:install

            -   name: Build Sass assets
                run: php bin/console sass:build

            -   name: Tests
                run: vendor/bin/phpunit
